#!/usr/bin/env bash

#   Copyright The containerd Authors.

#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at

#       http://www.apache.org/licenses/LICENSE-2.0

#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

#
# Deploy the cri-containerd release tarball to gcs.
#
set -eu -o pipefail

ROOT=${GOPATH}/src/github.com/containerd/containerd
BUCKET="gs://cri-containerd-release"

rm -rf "${HOME}/google-cloud-sdk"
export CLOUDSDK_CORE_DISABLE_PROMPTS=1
curl https://sdk.cloud.google.com | bash > /dev/null
gcloud version

openssl aes-256-cbc -K $encrypted_5a565171e51f_key -iv $encrypted_5a565171e51f_iv -in "${ROOT}/script/release/gcp-secret.json.enc" -out gcp-secret.json -d
gcloud auth activate-service-account --key-file gcp-secret.json --project=k8s-cri-containerd

for file in $(ls "${ROOT}"/releases/cri/*.tar.gz.sha256); do
  output="$(gsutil cp -n "${file}" "${BUCKET}" 2>&1)"
  if [[ "$output" =~ "Skipping existing item" ]];then
    echo "$(basename ${file}) already exists, skip the release tarball"
    continue
  fi
  gsutil cp "${file%.sha256}" "${BUCKET}"
done
