#!/usr/bin/env bash

#   Copyright The containerd Authors.

#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at

#       http://www.apache.org/licenses/LICENSE-2.0

#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

#
# Releases and publishes cri-containerd release tarball.
#
set -eu -o pipefail

if [[ -z "${VERSION:-}" ]]; then
  echo "VERSION is not set"
  exit 1
fi

ROOT=${GOPATH}/src/github.com/containerd/containerd
CRI_COMMIT=$(grep github.com/containerd/cri ${ROOT}/vendor.conf | awk '{print $2}')

go get -d github.com/containerd/cri/...
cd $GOPATH/src/github.com/containerd/cri
git checkout $CRI_COMMIT
make clean
make release TARBALL_PREFIX=cri-containerd LOCAL_RELEASE=true VERSION=${VERSION} VENDOR=${ROOT}/vendor.conf
make release TARBALL_PREFIX=cri-containerd-cni LOCAL_RELEASE=true INCLUDE_CNI=true VERSION=${VERSION} VENDOR=${ROOT}/vendor.conf

mkdir -p ${ROOT}/releases/cri
cp _output/*.tar.gz ${ROOT}/releases/cri
cp _output/*.tar.gz.sha256 ${ROOT}/releases/cri
