version: "2"
linters:
  enable:
    - copyloopvar
    - depguard
    - dupword
    - gosec
    - misspell
    - nolintlint
    - revive
    - unconvert
  disable:
    - errcheck
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/opencontainers/runc
              desc: We don't want to depend on runc (libcontainer), unless there is no other option; see https://github.com/opencontainers/runc/issues/3028.
    gosec:
      excludes:
        - G204
        - G305
        - G306
        - G402
        - G404
        - G115
    nolintlint:
      allow-unused: true
    staticcheck:
      checks:
        - '-QF1003'
        - '-QF1004'
        - '-QF1008'
        - '-ST1013'
        - '-ST1015'
        - '-ST1019'

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: cmd[\\/]containerd[\\/]builtins[\\/]
        text: 'blank-imports:'
      - path: contrib[\\/]fuzz[\\/]
        text: 'exported: func name will be used as fuzz.Fuzz'
      - path: archive[\\/]tarheader[\\/]
        text: unnecessary conversion
      - path: integration[\\/]client
        text: 'dot-imports:'
      - linters:
          - revive
        text: if-return
      - linters:
          - revive
        text: empty-block
      - linters:
          - revive
        text: superfluous-else
      - linters:
          - revive
        text: unused-parameter
      - linters:
          - revive
        text: unreachable-code
      - linters:
          - revive
        text: redefines-builtin-id
    paths:
      - api
      - cluster
      - docs
      - docs/man
      - releases
      - test
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - api
      - cluster
      - docs
      - docs/man
      - releases
      - test
      - third_party$
      - builtin$
      - examples$
