version: "2"
linters:
  enable:
    - copyloopvar # Checks for loop variable copies in Go 1.22+
    - depguard # Checks for dependencies that should not be (re)introduced. See "settings" for further details.
    - dupword # Checks for duplicate words in the source code
    - gosec
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unused
    - usetesting
  disable:
    - errcheck
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/opencontainers/runc
              desc: We don't want to depend on runc (libcontainer), unless there is no other option; see https://github.com/opencontainers/runc/issues/3028.
    forbidigo:
      forbid:
        - pkg: ^regexp$
          msg: Use internal/lazyregexp.New instead.
    gosec:
      # The following issues surfaced when `gosec` linter
      # was enabled. They are temporarily excluded to unblock
      # the existing workflow, but still to be addressed by
      # future works.
      excludes:
        - G204
        - G305
        - G306
        - G402
        - G404
        - G115
        - G103
        - G104
        - G301
        - G302
        - G304
    nolintlint:
      allow-unused: true
    revive:
      rules:
        - name: package-comments
          disabled: true
    staticcheck:
      checks:
        - all
        - -QF1008 # Omit embedded fields from selector expression
        - -ST1000 # Incorrect or missing package comment
        - -ST1020 # The documentation of an exported function should start with the function’s name
        - -ST1021 # The documentation of an exported type should start with type’s name
  exclusions:
    generated: lax
    rules:
      - path: cmd[\\/]containerd[\\/]builtins[\\/]
        text: 'blank-imports:'
      - path: contrib[\\/]fuzz[\\/]
        text: 'exported: func name will be used as fuzz.Fuzz'
      - path: archive[\\/]tarheader[\\/]
        # conversion is necessary on Linux, unnecessary on macOS
        text: unnecessary conversion
      - path: integration[\\/]client
        text: 'dot-imports:'
      - linters:
          - revive
        text: if-return
      - linters:
          - revive
        text: empty-block
      - linters:
          - revive
        text: superfluous-else
      - linters:
          - revive
        text: unused-parameter
      - linters:
          - revive
        text: unreachable-code
      - linters:
          - revive
        text: redefines-builtin-id
      - linters:
          - forbidigo
        text: 'use of `regexp.MustCompile` forbidden'
        path: _test\.go
    paths:
      - api
      - cluster
      - docs
      - docs/man
      - releases
      - test
    # Log a warning if an exclusion rule is unused.
    warn-unused: true
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: strict
    paths:
      - api
      - cluster
      - docs
      - docs/man
      - releases
      - test
