linters:
  enable:
    - structcheck
    - varcheck
    - staticcheck
    - unconvert
    - gofmt
    - goimports
    - revive
    - ineffassign
    - vet
    - unused
    - misspell
    - gosec
    - exportloopref # Checks for pointers to enclosing loop variables
    - tenv # Detects using os.Setenv instead of t.Setenv since Go 1.17
    - depguard # Checks if package imports are in a list of acceptable packages
  disable:
    - errcheck

issues:
  include:
    - EXC0002
  max-issues-per-linter: 0
  max-same-issues: 0

  # Only using / doesn't work due to https://github.com/golangci/golangci-lint/issues/1398.
  exclude-rules:
    - path: 'cmd[\\/]containerd[\\/]builtins[\\/]'
      text: "blank-imports:"
    - path: 'contrib[\\/]fuzz[\\/]'
      text: "exported: func name will be used as fuzz.Fuzz"

linters-settings:
  gosec:
    # The following issues surfaced when `gosec` linter
    # was enabled. They are temporarily excluded to unblock
    # the existing workflow, but still to be addressed by
    # by future works.
    excludes:
      - G204
      - G305
      - G306
      - G402
      - G404
  depguard:
    list-type: denylist
    include-go-root: true
    packages-with-error-message:
      - io/ioutil: "deprecated in 1.16 (see https://go.dev/doc/go1.16#ioutil)"

run:
  timeout: 8m
  skip-dirs:
    - api
    - cluster
    - design
    - docs
    - docs/man
    - releases
    - reports
    - test # e2e scripts
