linters:
  enable:
    - structcheck
    - varcheck
    - staticcheck
    - unconvert
    - gofmt
    - goimports
    - revive
    - ineffassign
    - vet
    - unused
    - misspell
    - exportloopref # Checks for pointers to enclosing loop variables
    - importas # Enforces consistent import aliases
    - stylecheck # Stylecheck is a replacement for golint
    - bidichk # Checks for dangerous unicode character sequence
  disable:
    - errcheck

issues:
  include:
    - EXC0002

run:
  timeout: 8m
  skip-dirs:
    - api
    - design
    - docs
    - docs/man
