linters:
  enable:
    - structcheck
    - varcheck
    - staticcheck
    - unconvert
    - gofmt
    - goimports
    - golint
    - ineffassign
    - vet
    - unused
    - misspell
  disable:
    - errcheck

issues:
  include:
    - EXC0002

run:
  timeout: 8m
  skip-dirs:
    - api
    - design
    - docs
    - docs/man
