#!/usr/bin/env bash
set -eu -o pipefail

vndr 2>&1 | grep -v -i clone

DIFF_PATH="vendor/"
DIFF=$(git status --porcelain -- "$DIFF_PATH")

if [ "$DIFF" ]; then
    echo
    echo "These files were modified:"
    echo
    echo "$DIFF"
    echo
    exit 1
else
    echo "$DIFF_PATH is correct"
fi
