//go:build !no_grpc

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: services/selinux/v1/selinux.proto

package selinux

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SelinuxClient is the client API for Selinux service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SelinuxClient interface {
	InitLabel(ctx context.Context, in *InitLabelRequest, opts ...grpc.CallOption) (*InitLabelResponse, error)
	ReleaseLabel(ctx context.Context, in *ReleaseLabelRequest, opts ...grpc.CallOption) (*ReleaseLabelResponse, error)
}

type selinuxClient struct {
	cc grpc.ClientConnInterface
}

func NewSelinuxClient(cc grpc.ClientConnInterface) SelinuxClient {
	return &selinuxClient{cc}
}

func (c *selinuxClient) InitLabel(ctx context.Context, in *InitLabelRequest, opts ...grpc.CallOption) (*InitLabelResponse, error) {
	out := new(InitLabelResponse)
	err := c.cc.Invoke(ctx, "/containerd.services.serlinux.v1.Selinux/InitLabel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *selinuxClient) ReleaseLabel(ctx context.Context, in *ReleaseLabelRequest, opts ...grpc.CallOption) (*ReleaseLabelResponse, error) {
	out := new(ReleaseLabelResponse)
	err := c.cc.Invoke(ctx, "/containerd.services.serlinux.v1.Selinux/ReleaseLabel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SelinuxServer is the server API for Selinux service.
// All implementations must embed UnimplementedSelinuxServer
// for forward compatibility
type SelinuxServer interface {
	InitLabel(context.Context, *InitLabelRequest) (*InitLabelResponse, error)
	ReleaseLabel(context.Context, *ReleaseLabelRequest) (*ReleaseLabelResponse, error)
	mustEmbedUnimplementedSelinuxServer()
}

// UnimplementedSelinuxServer must be embedded to have forward compatible implementations.
type UnimplementedSelinuxServer struct {
}

func (UnimplementedSelinuxServer) InitLabel(context.Context, *InitLabelRequest) (*InitLabelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitLabel not implemented")
}
func (UnimplementedSelinuxServer) ReleaseLabel(context.Context, *ReleaseLabelRequest) (*ReleaseLabelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseLabel not implemented")
}
func (UnimplementedSelinuxServer) mustEmbedUnimplementedSelinuxServer() {}

// UnsafeSelinuxServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SelinuxServer will
// result in compilation errors.
type UnsafeSelinuxServer interface {
	mustEmbedUnimplementedSelinuxServer()
}

func RegisterSelinuxServer(s grpc.ServiceRegistrar, srv SelinuxServer) {
	s.RegisterService(&Selinux_ServiceDesc, srv)
}

func _Selinux_InitLabel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitLabelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SelinuxServer).InitLabel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containerd.services.serlinux.v1.Selinux/InitLabel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SelinuxServer).InitLabel(ctx, req.(*InitLabelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Selinux_ReleaseLabel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseLabelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SelinuxServer).ReleaseLabel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containerd.services.serlinux.v1.Selinux/ReleaseLabel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SelinuxServer).ReleaseLabel(ctx, req.(*ReleaseLabelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Selinux_ServiceDesc is the grpc.ServiceDesc for Selinux service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Selinux_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "containerd.services.serlinux.v1.Selinux",
	HandlerType: (*SelinuxServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitLabel",
			Handler:    _Selinux_InitLabel_Handler,
		},
		{
			MethodName: "ReleaseLabel",
			Handler:    _Selinux_ReleaseLabel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/selinux/v1/selinux.proto",
}
