#!/usr/bin/env bash
# Generate HTML gRPC API docs from proto files

set -eu -o pipefail

target=docs/api
templates=docs/grpc-templates
url_base=/api

mkdir -p $target
cp "$templates/index.header.html" "$target/index.html"

for pkg in $(find api -name '*.proto' -printf "%h\n" | sort | uniq); do
    protoc \
        --html_out="template_root=$templates,url_root=$url_base:$target" \
        --proto_path=/go/src/ \
        --proto_path=./protobuf/ \
        --proto_path=./vendor/github.com/gogo/protobuf/ \
        $PWD/$pkg/*.proto
    cat "$target/index.fragment.html" >> "$target/index.html"
done

rm -f "$target/index.fragment.html"
cat "$templates/index.footer.html" >> "$target/index.html"
