#!/usr/bin/env bash
set -eu -o pipefail

mkdir -p docs/grpc

target=docs/grpc
templates=docs/grpc-templates

cp "$templates/index.header.html" "$target/index.html"

for pkg in $(find api -name '*.proto' -printf "%h\n" | sort | uniq); do
    protoc \
        --html_out="template_root=$templates,url_root=/:$target" \
        --proto_path=/go/src/ \
        --proto_path=./protobuf/ \
        --proto_path=./vendor/github.com/gogo/protobuf/ \
        $PWD/$pkg/*.proto
    cat "$target/index.fragment.html" >> "$target/index.html"
done

rm -f "$target/index.fragment.html"
cat "$templates/index.footer.html" >> "$target/index.html"
