---
- name: "Get kubernetes latest stable release version"
  command: >
      curl -L -s https://dl.k8s.io/release/stable.txt
  changed_when: false
  register: k8s_stable_release

- set_fact: 
    k8s_stable_release={{ k8s_stable_release.stdout | regex_replace('^v([0-9])+\\.([0-9]+)\\.[0-9]+', 'v\\1.\\2') }}

- name: "Add gpg key ({{ ansible_distribution }})"
  apt_key:
    url: "https://pkgs.k8s.io/core:/stable:/{{ k8s_stable_release }}/deb/Release.key"
    state: present
  when: ansible_os_family == "Debian"

- name: "Add kubernetes source list ({{ ansible_distribution }})"
  apt_repository:
    repo: "deb https://pkgs.k8s.io/core:/stable:/{{ k8s_stable_release }}/deb/ /"
    state: present
    filename: "kubernetes"
  when: ansible_os_family == "Debian"

- name: "Update the repository cache ({{ ansible_distribution }})"
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: "Add Kubernetes repository and install gpg key (CentOS)"
  yum_repository:
    name: kubernetes
    description: Kubernetes repository
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgcheck: yes
    enabled: yes
    repo_gpgcheck: yes
    gpgkey:
      - https://packages.cloud.google.com/yum/doc/yum-key.gpg
      - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  when: ansible_distribution == "CentOS"

- name: "Disable SELinux (CentOS)"
  selinux:
    state: disabled
  when: ansible_distribution == "CentOS"

- name: "Install kubelet,kubeadm,kubectl (CentOS)"
  yum: state=present name={{ item }}
  with_items:
    - kubelet
    - kubeadm
    - kubectl
  when: ansible_distribution == "CentOS"

- name: "Install kubelet, kubeadm, kubectl ({{ ansible_distribution }})"
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - kubelet
    - kubeadm
    - kubectl
  when: ansible_os_family == "Debian"
