#!/usr/bin/env bash

#   Copyright The containerd Authors.

#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at

#       http://www.apache.org/licenses/LICENSE-2.0

#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.


#
# Builds a specific version of libseccomp and installs in /usr/local
#
set -eu -o pipefail

set -x

export SECCOMP_VERSION=2.5.5
SECCOMP_PATH=$(mktemp -d)
export SECCOMP_PATH
curl -fsSL "https://github.com/seccomp/libseccomp/releases/download/v${SECCOMP_VERSION}/libseccomp-${SECCOMP_VERSION}.tar.gz" | tar -xzC "$SECCOMP_PATH" --strip-components=1
(
	cd "$SECCOMP_PATH"
	./configure --prefix=/usr/local
	make
	sudo make install
	sudo ldconfig
)

rm -rf "$SECCOMP_PATH"
