#!/usr/bin/env bash

#   Copyright The containerd Authors.

#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at

#       http://www.apache.org/licenses/LICENSE-2.0

#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

#
# Builds and installs critools including critest and crictl
# to /usr/local/bin.
#
set -eu -o pipefail

go get -u github.com/onsi/ginkgo/ginkgo
CRITEST_COMMIT=2bf7674922a424337d7580a08166d666c6802818 # v1.18.0-100-g2bf7674
git clone https://github.com/kubernetes-sigs/cri-tools.git "$GOPATH"/src/github.com/kubernetes-sigs/cri-tools
cd "$GOPATH"/src/github.com/kubernetes-sigs/cri-tools
git checkout "$CRITEST_COMMIT"
make
sudo make install -e BINDIR=${DESTDIR:=''}/usr/local/bin
cat << EOF | sudo tee ${DESTDIR}/etc/crictl.yaml
runtime-endpoint: unix:///run/containerd/containerd.sock
EOF
