# Detects breaking changes in protobuf files using buf.
# This check can be bypassed by adding the 'breaking-api-change' label to the PR.
# For more info: https://buf.build/docs/bsr/ci-cd/github-actions/

name: Protobuf

on:
  pull_request:
    branches: ['main', 'release/**']
    types: [opened, synchronize, reopened, labeled, unlabeled]
    paths:
      - 'api/**/*.proto'
      - 'api/buf.yaml'

permissions:
  contents: read
  pull-requests: read

jobs:
  breaking:
    name: Detect breaking API changes
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: bufbuild/buf-action@fd21066df7214747548607aaa45548ba2b9bc1ff # v1.4.0
        with:
          version: 1.63.0
          github_token: ${{ secrets.GITHUB_TOKEN }}
          input: 'api'
          breaking: ${{ !contains(github.event.pull_request.labels.*.name, 'breaking-api-change') }}
          lint: false
          format: false
          pr_comment: false
