on: pull_request

name: Build

jobs:
  build:
    name: Build
    runs-on: [self-hosted, linux, ARM64]

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.4'
