name: Build
on:
  push:
    branches:
      - master
      - 'release/**'
  pull_request:
    branches:
      - master
      - 'release/**'

jobs:
  binaries:
    name: Binaries
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-2019]

    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.8'

      - name: Set env
        shell: bash
        run: |
          echo "::set-env name=GOPATH::${{ github.workspace }}"
          echo "::add-path::${{ github.workspace }}/bin"
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: src/github.com/containerd/containerd

      - name: Install Linux dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get install -y btrfs-tools libseccomp-dev
      - name: Make
        run: |
          make build
          make binaries
        working-directory: src/github.com/containerd/containerd

  man:
    name: Mans
    runs-on: ubuntu-18.04
    timeout-minutes: 5

    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.8'

      - name: Set env
        shell: bash
        run: |
          echo "::set-env name=GOPATH::${{ github.workspace }}"
          echo "::add-path::${{ github.workspace }}/bin"
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: src/github.com/containerd/containerd

      - name: Install dependencies
        run: go get -u github.com/cpuguy83/go-md2man

      - name: Make
        run: make man
        working-directory: src/github.com/containerd/containerd