name: Links

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Every day at midnight
  pull_request:
    paths:
      - ".github/workflows/links.yml"

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    if: github.repository == 'containerd/containerd'
    name: lychee
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: lycheeverse/lychee-action@8646ba30535128ac92d33dfc9133794bfdd9b411 # v2.8.0
        with:
          # Fail action on broken links
          fail: true
          args: --root-dir "$(pwd)" --exclude nssm\.cc --exclude-path vendor --exclude-path releases --timeout 30 --no-progress './**/*.md'
          format: markdown
          # Write GitHub job summary
          jobSummary: true
