name: Publish Test Results

on:
   workflow_run:
      workflows: ["CI"]
      types:
         - completed

jobs:
  test-results:
    runs-on: ubuntu-latest
    name: Publish Test Results
    if: >
        github.event.workflow_run.conclusion != 'skipped' && (
          github.event.workflow_run.head_repository.full_name != github.repository
        )
    steps:
      - name: Download Artifacts
        uses: actions/github-script@v3.1.0
        with:
          script: |
              var fs = require('fs');
              var path = require('path');
              var artifacts_path = path.join('${{github.workspace}}', 'artifacts')
              fs.mkdirSync(artifacts_path, { recursive: true })

              var artifacts = await github.actions.listWorkflowRunArtifacts({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: ${{ github.event.workflow_run.id }},
              });

              for (const artifact of artifacts.data.artifacts) {
                var download = await github.actions.downloadArtifact({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    artifact_id: artifact.id,
                    archive_format: 'zip',
                });
                var artifact_path = path.join(artifacts_path, `${artifact.name}.zip`)
                fs.writeFileSync(artifact_path, Buffer.from(download.data));
                console.log(`Downloaded ${artifact_path}`);
              }
      - name: Extract Artifacts
        run: |
          for file in artifacts/*.zip
          do
            if [ -f "$file" ]
            then
              dir="${file/%.zip/}"
              mkdir -p "$dir"
              unzip -d "$dir" "$file"
            fi
          done
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: artifacts/*/**/*.xml
          check_name: Test Results
          comment_on_pr: true
          commit: ${{ github.event.workflow_run.head_sha }}