# Workflow intended to periodically run the Windows Hyper-V Integration test workflow.

name: Windows Hyper-V Periodic Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:

  triggerWinIntegration:
    # NOTE: the following permissions are required by `google-github-actions/auth`:
    permissions:
      contents: 'read'
      id-token: 'write'
    if: github.repository == 'containerd/containerd'
    # NOTE(aznashwan, 11/24/21): GitHub actions do not currently support referencing
    # or evaluating any kind of variables in the `uses` clause, but this will
    # ideally be added in the future in which case the hardcoded reference to the
    # upstream containerd repository should be replaced with the following to
    # potentially allow contributors to enable periodic Windows tests on forks as well:
    # uses: "${{ github.repository }}/.github/workflows/windows-hyperv-periodic.yml@${{ github.ref_name }}"
    uses: containerd/containerd/.github/workflows/windows-hyperv-periodic.yml@main
    secrets:
      AZURE_SUB_ID: "${{ secrets.AZURE_SUB_ID }}"
      AZURE_CREDS: "${{ secrets.AZURE_CREDS }}"
      GCP_SERVICE_ACCOUNT: "${{ secrets.GCP_SERVICE_ACCOUNT }}"
      GCP_WORKLOAD_IDENTITY_PROVIDER: "${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}"
