# commit to be tagged for new release
commit = "HEAD"

project_name = "containerd"
github_repo = "containerd/containerd"
sub_path = "api"
ignore_deps = [ "github.com/containerd/containerd" ]

# previous release
previous = "api/v1.9.0"

pre_release = true

preface = """\
The 11th release for the containerd 1.x API aligns with the containerd 2.2 release.
"""
