//
//Copyright The containerd Authors.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.1
// source: github.com/containerd/containerd/pkg/cri/server/imageverifier/v1/image_verifier.proto

package imageverifier

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerifyImageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageName   string `protobuf:"bytes,1,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	ImageDigest string `protobuf:"bytes,2,opt,name=image_digest,json=imageDigest,proto3" json:"image_digest,omitempty"`
}

func (x *VerifyImageRequest) Reset() {
	*x = VerifyImageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_containerd_containerd_pkg_cri_server_imageverifier_v1_image_verifier_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyImageRequest) ProtoMessage() {}

func (x *VerifyImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_containerd_containerd_pkg_cri_server_imageverifier_v1_image_verifier_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyImageRequest.ProtoReflect.Descriptor instead.
func (*VerifyImageRequest) Descriptor() ([]byte, []int) {
	return file_github_com_containerd_containerd_pkg_cri_server_imageverifier_v1_image_verifier_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyImageRequest) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *VerifyImageRequest) GetImageDigest() string {
	if x != nil {
		return x.ImageDigest
	}
	return ""
}

type VerifyImageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok     bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *VerifyImageResponse) Reset() {
	*x = VerifyImageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_containerd_containerd_pkg_cri_server_imageverifier_v1_image_verifier_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyImageResponse) ProtoMessage() {}

func (x *VerifyImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_containerd_containerd_pkg_cri_server_imageverifier_v1_image_verifier_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyImageResponse.ProtoReflect.Descriptor instead.
func (*VerifyImageResponse) Descriptor() ([]byte, []int) {
	return file_github_com_containerd_containerd_pkg_cri_server_imageverifier_v1_image_verifier_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyImageResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *VerifyImageResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_github_com_containerd_containerd_pkg_cri_server_imageverifier_v1_image_verifier_proto protoreflect.FileDescriptor

var file_github_com_containerd_containerd_pkg_cri_server_imageverifier_v1_image_verifier_proto_rawDesc = []byte{
	0x0a, 0x55, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65,
	0x72, 0x64, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x72, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2f,
	0x76, 0x31, 0x2f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1c, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x64, 0x2e, 0x63, 0x72, 0x69, 0x2e, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x76, 0x65, 0x72,
	0x69, 0x66, 0x69, 0x65, 0x72, 0x22, 0x56, 0x0a, 0x12, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x5f, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x22, 0x3d, 0x0a,
	0x13, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x02, 0x6f, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x32, 0x83, 0x01, 0x0a,
	0x0d, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x72,
	0x0a, 0x0b, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x30, 0x2e,
	0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e, 0x63, 0x72, 0x69, 0x2e, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x31, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e, 0x63, 0x72, 0x69,
	0x2e, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x50, 0x5a, 0x4e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2f, 0x63, 0x6f, 0x6e, 0x74,
	0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x72, 0x69, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x76, 0x65, 0x72, 0x69, 0x66,
	0x69, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x3b, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x76, 0x65, 0x72, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_containerd_containerd_pkg_cri_server_imageverifier_v1_image_verifier_proto_rawDescOnce sync.Once
	file_github_com_containerd_containerd_pkg_cri_server_imageverifier_v1_image_verifier_proto_rawDescData = file_github_com_containerd_containerd_pkg_cri_server_imageverifier_v1_image_verifier_proto_rawDesc
)

func file_github_com_containerd_containerd_pkg_cri_server_imageverifier_v1_image_verifier_proto_rawDescGZIP() []byte {
	file_github_com_containerd_containerd_pkg_cri_server_imageverifier_v1_image_verifier_proto_rawDescOnce.Do(func() {
		file_github_com_containerd_containerd_pkg_cri_server_imageverifier_v1_image_verifier_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_containerd_containerd_pkg_cri_server_imageverifier_v1_image_verifier_proto_rawDescData)
	})
	return file_github_com_containerd_containerd_pkg_cri_server_imageverifier_v1_image_verifier_proto_rawDescData
}

var file_github_com_containerd_containerd_pkg_cri_server_imageverifier_v1_image_verifier_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_containerd_containerd_pkg_cri_server_imageverifier_v1_image_verifier_proto_goTypes = []interface{}{
	(*VerifyImageRequest)(nil),  // 0: containerd.cri.imageverifier.VerifyImageRequest
	(*VerifyImageResponse)(nil), // 1: containerd.cri.imageverifier.VerifyImageResponse
}
var file_github_com_containerd_containerd_pkg_cri_server_imageverifier_v1_image_verifier_proto_depIdxs = []int32{
	0, // 0: containerd.cri.imageverifier.ImageVerifier.VerifyImage:input_type -> containerd.cri.imageverifier.VerifyImageRequest
	1, // 1: containerd.cri.imageverifier.ImageVerifier.VerifyImage:output_type -> containerd.cri.imageverifier.VerifyImageResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() {
	file_github_com_containerd_containerd_pkg_cri_server_imageverifier_v1_image_verifier_proto_init()
}
func file_github_com_containerd_containerd_pkg_cri_server_imageverifier_v1_image_verifier_proto_init() {
	if File_github_com_containerd_containerd_pkg_cri_server_imageverifier_v1_image_verifier_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_containerd_containerd_pkg_cri_server_imageverifier_v1_image_verifier_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyImageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_containerd_containerd_pkg_cri_server_imageverifier_v1_image_verifier_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyImageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_containerd_containerd_pkg_cri_server_imageverifier_v1_image_verifier_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_containerd_containerd_pkg_cri_server_imageverifier_v1_image_verifier_proto_goTypes,
		DependencyIndexes: file_github_com_containerd_containerd_pkg_cri_server_imageverifier_v1_image_verifier_proto_depIdxs,
		MessageInfos:      file_github_com_containerd_containerd_pkg_cri_server_imageverifier_v1_image_verifier_proto_msgTypes,
	}.Build()
	File_github_com_containerd_containerd_pkg_cri_server_imageverifier_v1_image_verifier_proto = out.File
	file_github_com_containerd_containerd_pkg_cri_server_imageverifier_v1_image_verifier_proto_rawDesc = nil
	file_github_com_containerd_containerd_pkg_cri_server_imageverifier_v1_image_verifier_proto_goTypes = nil
	file_github_com_containerd_containerd_pkg_cri_server_imageverifier_v1_image_verifier_proto_depIdxs = nil
}
